In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data_set.csv")
df

,Match no.,team 1,team 2,runs 1,runs 2,stadium,Overs left,runs2_projected
0,1,MI,CSK,162,166,ABU DHABI,4,172
1,2,DC,PBKS,157,157,DUBAI,0,157
2,3,RCB,SRH,163,153,DUBAI,2,156
3,4,RR,CSK,216,200,SHARJAH,0,200
4,5,MI,KKR,195,146,ABU DHABI,0,146
5,6,PBKS,RCB,206,109,DUBAI,18,128
6,7,DC,CSK,175,131,DUBAI,0,131
7,8,SRH,KKR,142,145,ABU DHABI,12,161
8,9,PBKS,RR,223,226,SHARJAH,3,232
9,10,RCB,MI,201,201,DUBAI,0,201
10,11,SRH,DC,162,147,ABU DHABI,0,147
11,12,KKR,RR,174,137,DUBAI,0,137
12,13,MI,PBKS,191,143,ABU DHABI,0,143
13,14,SRH,CSK,164,157,DUBAI,0,157
14,15,RR,RCB,154,158,ABU DHABI,5,165
15,16,DC,KKR,228,210,SHARJAH,0,210
16,17,MI,SRH,208,174,SHARJAH,0,174
17,18,PBKS,CSK,178,181,DUBAI,14,205
18,19,DC,RCB,196,137,DUBAI,0,137
19,20,MI,RR,193,136,ABU DHABI,11,150
20,21,KKR,CSK,167,157,ABU DHABI,0,157
21,22,SRH,PBKS,201,132,DUBAI,19,157
22,23,DC,RR,184,138,ABU DHABI,2,140
23,24,KKR,PBKS,164,162,ABU DHABI,0,162
24,25,RCB,CSK,169,132,DUBAI,0,132
25,26,SRH,RR,158,163,DUBAI,1,164
26,27,DC,MI,162,166,ABU DHABI,2,169
27,28,RCB,KKR,194,112,SHARJAH,0,112
28,29,CSK,SRH,167,147,DUBAI,0,147
29,30,DC,RR,161,148,DUBAI,0,148
30,31,RCB,PBKS,171,177,SHARJAH,0,177
31,32,KKR,MI,148,149,ABU DHABI,19,177
32,33,RR,RCB,177,179,DUBAI,12,199
33,34,CSK,DC,179,185,SHARJAH,6,195
34,35,KKR,SRH,163,163,ABU DHABI,0,163
35,36,MI,PBKS,176,176,DUBAI,0,176
36,37,CSK,RR,125,126,ABU DHABI,15,144
37,38,DC,PBKS,164,167,DUBAI,6,176
38,39,KKR,RCB,84,85,ABU DHABI,39,126
39,40,RR,SRH,154,156,DUBAI,11,172
40,41,CSK,MI,114,116,SHARJAH,46,188
41,42,KKR,DC,194,135,ABU DHABI,0,135
42,43,PBKS,SRH,126,114,DUBAI,1,115
43,44,RCB,CSK,145,150,DUBAI,8,161
44,45,MI,RR,195,196,ABU DHABI,10,214
45,46,KKR,PBKS,149,150,SHARJAH,7,159
46,47,SRH,DC,219,131,DUBAI,6,138
47,48,RCB,MI,164,166,ABU DHABI,5,173
48,49,KKR,CSK,172,178,DUBAI,0,178
49,50,PBKS,RR,185,186,ABU DHABI,15,213
50,51,DC,MI,110,111,DUBAI,34,155
51,52,RCB,SRH,120,121,SHARJAH,35,171
52,53,PBKS,CSK,153,154,ABU DHABI,7,164
53,54,KKR,RR,191,131,DUBAI,0,131
54,55,RCB,DC,152,154,ABU DHABI,6,162
55,56,MI,SRH,149,151,SHARJAH,17,176
56,57,MI,DC,200,143,DUBAI,0,143
57,58,RCB,SRH,131,132,ABU DHABI,2,134
58,59,DC,SRH,189,172,ABU DHABI,0,172
59,60,DC,MI,156,157,DUBAI,8,168

In [3]:
df2 = df.drop(columns=["Match no."],axis=1)

In [4]:
df2

   team 1 team 2  runs 1  runs 2    stadium  Overs left  runs2_projected
0      MI    CSK     162     166  ABU DHABI           4              172
1      DC   PBKS     157     157      DUBAI           0              157
2     RCB    SRH     163     153      DUBAI           2              156
3      RR    CSK     216     200    SHARJAH           0              200
4      MI    KKR     195     146  ABU DHABI           0              146
5    PBKS    RCB     206     109      DUBAI          18              128
6      DC    CSK     175     131      DUBAI           0              131
7     SRH    KKR     142     145  ABU DHABI          12              161
8    PBKS     RR     223     226    SHARJAH           3              232
9     RCB     MI     201     201      DUBAI           0              201
10    SRH     DC     162     147  ABU DHABI           0              147
11    KKR     RR     174     137      DUBAI           0              137
12     MI   PBKS     191     143  ABU DHABI           0              143
13    SRH    CSK     164     157      DUBAI           0              157
14     RR    RCB     154     158  ABU DHABI           5              165
15     DC    KKR     228     210    SHARJAH           0              210
16     MI    SRH     208     174    SHARJAH           0              174
17   PBKS    CSK     178     181      DUBAI          14              205
18     DC    RCB     196     137      DUBAI           0              137
19     MI     RR     193     136  ABU DHABI          11              150
20    KKR    CSK     167     157  ABU DHABI           0              157
21    SRH   PBKS     201     132      DUBAI          19              157
22     DC     RR     184     138  ABU DHABI           2              140
23    KKR   PBKS     164     162  ABU DHABI           0              162
24    RCB    CSK     169     132      DUBAI           0              132
25    SRH     RR     158     163      DUBAI           1              164
26     DC     MI     162     166  ABU DHABI           2              169
27    RCB    KKR     194     112    SHARJAH           0              112
28    CSK    SRH     167     147      DUBAI           0              147
29     DC     RR     161     148      DUBAI           0              148
30    RCB   PBKS     171     177    SHARJAH           0              177
31    KKR     MI     148     149  ABU DHABI          19              177
32     RR    RCB     177     179      DUBAI          12              199
33    CSK     DC     179     185    SHARJAH           6              195
34    KKR    SRH     163     163  ABU DHABI           0              163
35     MI   PBKS     176     176      DUBAI           0              176
36    CSK     RR     125     126  ABU DHABI          15              144
37     DC   PBKS     164     167      DUBAI           6              176
38    KKR    RCB      84      85  ABU DHABI          39              126
39     RR    SRH     154     156      DUBAI          11              172
40    CSK     MI     114     116    SHARJAH          46              188
41    KKR     DC     194     135  ABU DHABI           0              135
42   PBKS    SRH     126     114      DUBAI           1              115
43    RCB    CSK     145     150      DUBAI           8              161
44     MI     RR     195     196  ABU DHABI          10              214
45    KKR   PBKS     149     150    SHARJAH           7              159
46    SRH     DC     219     131      DUBAI           6              138
47    RCB     MI     164     166  ABU DHABI           5              173
48    KKR    CSK     172     178      DUBAI           0              178
49   PBKS     RR     185     186  ABU DHABI          15              213
50     DC     MI     110     111      DUBAI          34              155
51    RCB    SRH     120     121    SHARJAH          35              171
52   PBKS    CSK     153     154  ABU DHABI           7              164
53    KKR     RR     191     131      DUBAI           0              131
54    RCB     DC     152     154  ABU DHABI           6              162
55     MI    SRH     149     151    SHARJAH          17              176
56     MI     DC     200     143      DUBAI           0              143
57    RCB    SRH     131     132  ABU DHABI           2              134
58     DC    SRH     189     172  ABU DHABI           0              172
59     DC     MI     156     157      DUBAI           8              168

In [5]:
a = df2[df2["team 1"] == "MI"]
a

   team 1 team 2  runs 1  runs 2    stadium  Overs left  runs2_projected
0      MI    CSK     162     166  ABU DHABI           4              172
4      MI    KKR     195     146  ABU DHABI           0              146
12     MI   PBKS     191     143  ABU DHABI           0              143
16     MI    SRH     208     174    SHARJAH           0              174
19     MI     RR     193     136  ABU DHABI          11              150
35     MI   PBKS     176     176      DUBAI           0              176
44     MI     RR     195     196  ABU DHABI          10              214
55     MI    SRH     149     151    SHARJAH          17              176
56     MI     DC     200     143      DUBAI           0              143

In [6]:
MI_1 = a["runs 1"].mean()
MI_1

185.44444444444446

In [7]:
teams = df["team 1"].unique()
teams

array(['MI', 'DC', 'RCB', 'RR', 'PBKS', 'SRH', 'KKR', 'CSK'], dtype=object)

In [30]:
dit = {}
for i in teams:
    a = df2[df2["team 1"] == i]
    dit[i] = [a["runs 1"].mean(),a["runs 1"].sum()/a["runs 1"].mean()]

In [31]:
dit

{'MI': [185.44444444444446, 9.0],
 'DC': [171.0909090909091, 11.0],
 'RCB': [161.0, 10.0],
 'RR': [175.25, 4.0],
 'PBKS': [178.5, 6.0],
 'SRH': [174.33333333333334, 6.0],
 'KKR': [160.6, 10.0],
 'CSK': [146.25, 4.0]}

In [32]:
dit2 = {}
for i in teams:
    a = df2[df2["team 2"] == i]
    dit2[i] = [a["runs 2"].mean(),a["runs 2"].sum()/a["runs 2"].mean()

dit2

In [33]:
dit2

{'MI': [152.28571428571428, 7.0],
 'DC': [149.16666666666666, 6.0],
 'RCB': [133.6, 5.0],
 'RR': [158.7, 10.0],
 'PBKS': [158.0, 8.0],
 'SRH': [148.3, 10.0],
 'KKR': [153.25, 4.0],
 'CSK': [160.6, 10.0]}

In [12]:
df3 = pd.get_dummies(df,columns=['team 1','team 2','stadium'],drop_first = True)
df3.drop(columns=['Match no.'],axis = 1,inplace=True)
df3

,runs 1,runs 2,Overs left,runs2_projected,team 1_DC,team 1_KKR,team 1_MI,team 1_PBKS,team 1_RCB,team 1_RR,team 1_SRH,team 2_DC,team 2_KKR,team 2_MI,team 2_PBKS,team 2_RCB,team 2_RR,team 2_SRH,stadium_DUBAI,stadium_SHARJAH
0,162,166,4,172,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,157,157,0,157,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
2,163,153,2,156,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0
3,216,200,0,200,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
4,195,146,0,146,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0
5,206,109,18,128,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0
6,175,131,0,131,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7,142,145,12,161,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
8,223,226,3,232,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1
9,201,201,0,201,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
10,162,147,0,147,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
11,174,137,0,137,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0
12,191,143,0,143,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
13,164,157,0,157,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0
14,154,158,5,165,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
15,228,210,0,210,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
16,208,174,0,174,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1
17,178,181,14,205,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
18,196,137,0,137,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0
19,193,136,11,150,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
20,167,157,0,157,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,201,132,19,157,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0
22,184,138,2,140,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
23,164,162,0,162,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
24,169,132,0,132,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
25,158,163,1,164,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0
26,162,166,2,169,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
27,194,112,0,112,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1
28,167,147,0,147,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
29,161,148,0,148,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0
30,171,177,0,177,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1
31,148,149,19,177,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
32,177,179,12,199,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0
33,179,185,6,195,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
34,163,163,0,163,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
35,176,176,0,176,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
36,125,126,15,144,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
37,164,167,6,176,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
38,84,85,39,126,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
39,154,156,11,172,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0
40,114,116,46,188,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
41,194,135,0,135,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
42,126,114,1,115,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0
43,145,150,8,161,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
44,195,196,10,214,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
45,149,150,7,159,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1
46,219,131,6,138,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0
47,164,166,5,173,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
48,172,178,0,178,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
49,185,186,15,213,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
50,110,111,34,155,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
51,120,121,35,171,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1
52,153,154,7,164,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
53,191,131,0,131,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0
54,152,154,6,162,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0
55,149,151,17,176,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1
56,200,143,0,143,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0
57,131,132,2,134,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
58,189,172,0,172,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
59,156,157,8,168,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0

In [13]:
df3['runs 1'] = df3['runs 1']/max(df3['runs 1'])

In [14]:
df3['runs 2'] = df3['runs 2']/max(df3['runs 2'])

In [15]:
df3

,runs 1,runs 2,Overs left,runs2_projected,team 1_DC,team 1_KKR,team 1_MI,team 1_PBKS,team 1_RCB,team 1_RR,team 1_SRH,team 2_DC,team 2_KKR,team 2_MI,team 2_PBKS,team 2_RCB,team 2_RR,team 2_SRH,stadium_DUBAI,stadium_SHARJAH
0,0.710526,0.734513,4,172,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0.688596,0.694690,0,157,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
2,0.714912,0.676991,2,156,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0
3,0.947368,0.884956,0,200,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
4,0.855263,0.646018,0,146,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0
5,0.903509,0.482301,18,128,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0
6,0.767544,0.579646,0,131,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7,0.622807,0.641593,12,161,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
8,0.978070,1.000000,3,232,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1
9,0.881579,0.889381,0,201,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
10,0.710526,0.650442,0,147,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
11,0.763158,0.606195,0,137,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0
12,0.837719,0.632743,0,143,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
13,0.719298,0.694690,0,157,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0
14,0.675439,0.699115,5,165,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
15,1.000000,0.929204,0,210,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
16,0.912281,0.769912,0,174,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1
17,0.780702,0.800885,14,205,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0
18,0.859649,0.606195,0,137,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0
19,0.846491,0.601770,11,150,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
20,0.732456,0.694690,0,157,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,0.881579,0.584071,19,157,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0
22,0.807018,0.610619,2,140,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
23,0.719298,0.716814,0,162,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
24,0.741228,0.584071,0,132,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
25,0.692982,0.721239,1,164,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0
26,0.710526,0.734513,2,169,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
27,0.850877,0.495575,0,112,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1
28,0.732456,0.650442,0,147,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
29,0.706140,0.654867,0,148,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0
30,0.750000,0.783186,0,177,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1
31,0.649123,0.659292,19,177,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
32,0.776316,0.792035,12,199,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0
33,0.785088,0.818584,6,195,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
34,0.714912,0.721239,0,163,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
35,0.771930,0.778761,0,176,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
36,0.548246,0.557522,15,144,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
37,0.719298,0.738938,6,176,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
38,0.368421,0.376106,39,126,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
39,0.675439,0.690265,11,172,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0
40,0.500000,0.513274,46,188,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
41,0.850877,0.597345,0,135,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
42,0.552632,0.504425,1,115,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0
43,0.635965,0.663717,8,161,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
44,0.855263,0.867257,10,214,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0
45,0.653509,0.663717,7,159,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1
46,0.960526,0.579646,6,138,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0
47,0.719298,0.734513,5,173,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0
48,0.754386,0.787611,0,178,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0
49,0.811404,0.823009,15,213,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
50,0.482456,0.491150,34,155,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
51,0.526316,0.535398,35,171,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1
52,0.671053,0.681416,7,164,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
53,0.837719,0.579646,0,131,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0
54,0.666667,0.681416,6,162,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0
55,0.653509,0.668142,17,176,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1
56,0.877193,0.632743,0,143,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0
57,0.574561,0.584071,2,134,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
58,0.828947,0.761062,0,172,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
59,0.684211,0.694690,8,168,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0

In [16]:
df3.corr()

,runs 1,runs 2,Overs left,runs2_projected,team 1_DC,team 1_KKR,team 1_MI,team 1_PBKS,team 1_RCB,team 1_RR,team 1_SRH,team 2_DC,team 2_KKR,team 2_MI,team 2_PBKS,team 2_RCB,team 2_RR,team 2_SRH,stadium_DUBAI,stadium_SHARJAH
runs 1,1.000000,0.509283,-5.584711e-01,0.234964,0.026420,-1.395045e-01,0.234763,1.051489e-01,-1.332347e-01,0.053863,5.646884e-02,1.733009e-01,0.189690,-0.239289,0.029214,-0.064464,1.473419e-01,-1.959333e-01,0.062479,0.130589
runs 2,0.509283,1.000000,-4.215018e-01,0.847157,0.017447,-1.419620e-01,0.095479,1.096214e-01,-5.508124e-02,0.205818,-9.142174e-02,-4.909686e-02,0.002206,-0.010350,0.074207,-0.223197,9.653413e-02,-8.063439e-02,-0.129229,0.227463
Overs left,-0.558471,-0.421502,1.000000e+00,0.118017,-0.095706,-1.307482e-02,-0.087336,9.312269e-02,-4.358274e-02,0.005209,-1.515951e-02,-1.234417e-01,-0.098974,0.335955,-0.107029,0.235068,-4.794102e-02,-5.092686e-17,-0.120621,0.164547
runs2_projected,0.234964,0.847157,1.180168e-01,1.000000,-0.042241,-1.769587e-01,0.057433,1.792225e-01,-8.171849e-02,0.226262,-1.121784e-01,-1.209423e-01,-0.055687,0.190964,0.013020,-0.137142,8.407010e-02,-7.995478e-02,-0.208073,0.350159
team 1_DC,0.026420,0.017447,-9.570619e-02,-0.042241,1.000000,-2.118914e-01,-0.199037,-1.579345e-01,-2.118914e-01,-0.126629,-1.579345e-01,-1.579345e-01,0.046047,0.230333,0.067579,0.012987,1.926285e-02,-9.631427e-02,0.194126,-0.113173
team 1_KKR,-0.139505,-0.141962,-1.307482e-02,-0.176959,-0.211891,1.000000e+00,-0.187867,-1.490712e-01,-2.000000e-01,-0.119523,-1.490712e-01,-1.344706e-17,-0.119523,-0.023218,0.087706,0.026968,4.000000e-02,-8.000000e-02,-0.120331,-0.096314
team 1_MI,0.234763,0.095479,-8.733623e-02,0.057433,-0.199037,-1.878673e-01,1.000000,-1.400280e-01,-1.878673e-01,-0.112272,-1.400280e-01,1.555867e-02,0.074848,-0.152668,0.109847,-0.126660,6.262243e-02,6.262243e-02,-0.178967,0.042220
team 1_PBKS,0.105149,0.109621,9.312269e-02,0.179223,-0.157935,-1.490712e-01,-0.140028,1.000000e+00,-1.490712e-01,-0.089087,-1.111111e-01,-1.111111e-01,-0.089087,-0.121141,-0.130744,0.100504,1.490712e-01,-7.240725e-18,0.044845,-0.014358
team 1_RCB,-0.133235,-0.055081,-4.358274e-02,-0.081718,-0.211891,-2.000000e-01,-0.187867,-1.490712e-01,1.000000e+00,-0.119523,-1.490712e-01,-1.137828e-17,0.059761,0.116091,-0.043853,-0.134840,-2.000000e-01,1.600000e-01,-0.030083,0.134840
team 1_RR,0.053863,0.205818,5.209134e-03,0.226262,-0.126629,-1.195229e-01,-0.112272,-8.908708e-02,-1.195229e-01,1.000000,-8.908708e-02,-8.908708e-02,-0.071429,-0.097129,-0.104828,0.402911,-1.195229e-01,5.976143e-02,0.035956,0.046047
team 1_SRH,0.056469,-0.091422,-1.515951e-02,-0.112178,-0.157935,-1.490712e-01,-0.140028,-1.111111e-01,-1.490712e-01,-0.089087,1.000000e+00,2.592593e-01,0.133631,-0.121141,0.032686,-0.100504,-1.137828e-17,-1.490712e-01,0.156957,-0.157935
team 2_DC,0.173301,-0.049097,-1.234417e-01,-0.120942,-0.157935,-1.344706e-17,0.015559,-1.111111e-01,-1.137828e-17,-0.089087,2.592593e-01,1.000000e+00,-0.089087,-0.121141,-0.130744,-0.100504,-1.490712e-01,-1.490712e-01,-0.067267,-0.014358
team 2_KKR,0.189690,0.002206,-9.897355e-02,-0.055687,0.046047,-1.195229e-01,0.074848,-8.908708e-02,5.976143e-02,-0.071429,1.336306e-01,-8.908708e-02,1.000000,-0.097129,-0.104828,-0.080582,-1.195229e-01,-1.195229e-01,-0.233713,0.218723
team 2_MI,-0.239289,-0.010350,3.359547e-01,0.190964,0.230333,-2.321817e-02,-0.152668,-1.211406e-01,1.160909e-01,-0.097129,-1.211406e-01,-1.211406e-01,-0.097129,1.000000,-0.142546,-0.109576,-1.625272e-01,-1.625272e-01,-0.003492,-0.038016
team 2_PBKS,0.029214,0.074207,-1.070289e-01,0.013020,0.067579,8.770580e-02,0.109847,-1.307441e-01,-4.385290e-02,-0.104828,3.268602e-02,-1.307441e-01,-0.104828,-0.142546,1.000000,-0.118262,-1.754116e-01,-1.754116e-01,0.052769,0.067579
team 2_RCB,-0.064464,-0.223197,2.350678e-01,-0.137142,0.012987,2.696799e-02,-0.126660,1.005038e-01,-1.348400e-01,0.402911,-1.005038e-01,-1.005038e-01,-0.080582,-0.109576,-0.118262,1.000000,-1.348400e-01,-1.348400e-01,0.101409,-0.142857
team 2_RR,0.147342,0.096534,-4.794102e-02,0.084070,0.019263,4.000000e-02,0.062622,1.490712e-01,-2.000000e-01,-0.119523,-1.137828e-17,-1.490712e-01,-0.119523,-0.162527,-0.175412,-0.134840,1.000000e+00,-2.000000e-01,-0.030083,-0.096314
team 2_SRH,-0.195933,-0.080634,-5.092686e-17,-0.079955,-0.096314,-8.000000e-02,0.062622,-7.240725e-18,1.600000e-01,0.059761,-1.490712e-01,-1.490712e-01,-0.119523,-0.162527,-0.175412,-0.134840,-2.000000e-01,1.000000e+00,-0.030083,0.134840
stadium_DUBAI,0.062479,-0.129229,-1.206205e-01,-0.208073,0.194126,-1.203314e-01,-0.178967,4.484485e-02,-3.008284e-02,0.035956,1.569570e-01,-6.726728e-02,-0.233713,-0.003492,0.052769,0.101409,-3.008284e-02,-3.008284e-02,1.000000,-0.414329
stadium_SHARJAH,0.130589,0.227463,1.645475e-01,0.350159,-0.113173,-9.631427e-02,0.042220,-1.435768e-02,1.348400e-01,0.046047,-1.579345e-01,-1.435768e-02,0.218723,-0.038016,0.067579,-0.142857,-9.631427e-02,1.348400e-01,-0.414329,1.000000

In [17]:
import sklearn
from sklearn.linear_model import LinearRegression as lr
from sklearn.model_selection import train_test_split

In [18]:
x = df3.drop(columns=["runs 1","runs 2"],axis =1)
y1 = df3["runs 1"]
y2 = df3['runs 2']

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y1,test_size=0.8,random_state=1)

In [20]:
model = lr()

In [21]:
model.fit(x_train,y_train)

LinearRegression()

In [22]:
y_predict_runs1  =  model.predict(x_test)

In [23]:
y_predict_runs1

array([0.69267022, 0.75493887, 0.59820801, 0.79163895, 0.88253032,
       0.75252904, 0.92587291, 0.86820344, 1.29340376, 1.01659072,
       0.59275006, 0.75942833, 0.6715506 , 0.91008941, 0.78050661,
       0.69065014, 0.88210592, 0.64828195, 0.72252881, 0.71589559,
       0.6673933 , 0.68987731, 0.78002574, 1.08680769, 0.77517984,
       0.88711077, 0.86994567, 1.03089052, 0.96704971, 0.66446942,
       0.51354579, 0.93032643, 0.99742676, 0.75658604, 0.92953543,
       0.89915166, 0.83396499, 0.52219293, 0.64249602, 0.62031782,
       0.51437788, 0.67710255, 0.80874802, 0.76861394, 0.66897346,
       0.51462152, 1.17857367, 0.9121483 ])

In [24]:
y_test

39    0.675439
41    0.850877
2     0.714912
48    0.754386
50    0.482456
44    0.855263
33    0.785088
35    0.771930
40    0.500000
27    0.850877
24    0.741228
53    0.837719
46    0.960526
3     0.947368
26    0.710526
36    0.548246
21    0.881579
10    0.710526
52    0.671053
19    0.846491
42    0.552632
56    0.877193
17    0.780702
31    0.649123
49    0.811404
32    0.776316
47    0.719298
38    0.368421
55    0.653509
13    0.719298
22    0.807018
51    0.526316
30    0.750000
34    0.714912
23    0.719298
4     0.855263
14    0.675439
29    0.706140
28    0.732456
54    0.666667
58    0.828947
18    0.859649
59    0.684211
20    0.732456
25    0.692982
6     0.767544
45    0.653509
7     0.622807
Name: runs 1, dtype: float64

In [25]:
from sklearn.metrics import r2_score

In [26]:
r2scoreof_runs1 = r2_score(y_test, y_predict_runs1)

In [27]:
r2scoreof_runs1

-3.195646469750562